development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: extract-deploy-guides_development
  pool: 5
  username: root
  password:
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: extract-deploy-guides_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: extract-deploy-guides_production
  pool: 5
  username: root
  password:
